AWSTemplateFormatVersion: '2010-09-09'
Resources:
  GraphQL:
    Properties:
      CodeUri: s3://api.d2.report/37391636c0a18249a81a8bd659fb240a
      Events:
        AnyRequest:
          Properties:
            Method: ANY
            Path: /graphql
          Type: Api
      Handler: graphql.handler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
